name: Selenium - Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: windows-latest
     
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.1
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
   
      - name: Test with Selenium et unittest
        run: python -m unittest -v test_authentification test_creation_contrat_credit_auto